name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: read  # Required for GitHub Packages authentication

    env:
      # Supabase Configuration
      VITE_SUPABASE_URL: ${{ vars.VITE_SUPABASE_URL }}
      VITE_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY }}

      # SmartSuite Configuration
      VITE_SMARTSUITE_API_KEY: ${{ secrets.VITE_SMARTSUITE_API_KEY }}
      VITE_SMARTSUITE_WORKSPACE_ID: ${{ vars.VITE_SMARTSUITE_WORKSPACE_ID }}
      VITE_SMARTSUITE_PROJECTS_TABLE: ${{ vars.VITE_SMARTSUITE_PROJECTS_TABLE }}
      VITE_SMARTSUITE_VIDEOS_TABLE: ${{ vars.VITE_SMARTSUITE_VIDEOS_TABLE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@elevanaltd'
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ========== LOCAL SUPABASE SETUP FOR TESTS ==========
      # Local Supabase instance eliminates rate limits and provides isolated test environment
      # Test users are seeded automatically, matching local development workflow

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start local Supabase instance
        run: |
          supabase start

          # Wait for GoTrue to be ready (health check)
          echo "=== Waiting for GoTrue to be ready ==="
          timeout 60 bash -c 'until curl -f http://127.0.0.1:54321/auth/v1/health > /dev/null 2>&1; do echo "Waiting for GoTrue..."; sleep 2; done'
          echo "✅ GoTrue is ready"

      - name: Apply database migrations
        run: |
          # Apply migrations WITHOUT seed.sql (seed has TRUNCATE that might affect auth)
          # Using db push instead of db reset to skip automatic seeding
          supabase db push --local

          # Manually run seed AFTER test users are created
          echo "=== Schema initialized (migrations applied, seed deferred) ==="

      - name: Create test users via Auth Admin API
        run: |
          # Use Supabase Auth Admin API instead of direct SQL
          # This ensures proper GoTrue internal state (auth.users + auth.identities)
          # See: scripts/create-test-users-via-api.mjs for implementation details

          # Extract service role key from Supabase CLI
          export SUPABASE_SERVICE_ROLE_KEY=$(supabase status -o json | jq -r '.service_role_key')

          # Run Node.js script to create users via Auth API
          node scripts/create-test-users-via-api.mjs

          echo "=== Test users created via Auth Admin API ==="

      - name: Seed test data (projects, videos, scripts)
        run: |
          # Now run seed.sql AFTER test users exist
          # seed.sql has TRUNCATE commands that won't affect auth.users
          psql "postgresql://postgres:postgres@127.0.0.1:54322/postgres" < supabase/seed.sql

          echo "=== Test data seeded ==="

      - name: Override environment variables for local Supabase
        run: |
          # Use local Supabase instead of production for tests
          echo "VITE_SUPABASE_URL=http://127.0.0.1:54321" >> $GITHUB_ENV
          echo "VITE_SUPABASE_PUBLISHABLE_KEY=$(supabase status -o json | jq -r '.anon_key')" >> $GITHUB_ENV

          # Verify configuration
          echo "=== Local Supabase Configuration ==="
          echo "URL: http://127.0.0.1:54321"
          echo "Key: $(supabase status -o json | jq -r '.anon_key')"
      # ========== END LOCAL SUPABASE SETUP ==========

      # Temporarily disabled during GitHub Packages migration - package-lock.json will be generated by CI
      # - name: Validate lock file sync
      #   run: |
      #     # Detect package.json/package-lock.json desynchronization
      #     if ! npm install --package-lock-only --dry-run &>/dev/null; then
      #       echo "❌ ERROR: package-lock.json is out of sync with package.json"
      #       echo ""
      #       echo "This typically happens when package.json is updated but 'npm install' wasn't run."
      #       echo ""
      #       echo "To fix this issue:"
      #       echo "  1. Run 'npm install' locally"
      #       echo "  2. Commit the updated package-lock.json"
      #       echo "  3. Push your changes"
      #       exit 1
      #     fi
      #     echo "✅ Lock file is synchronized"

      - name: Install dependencies
        run: npm install  # Using npm install instead of npm ci to generate package-lock.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug - Verify shared-lib installation
        run: |
          echo "=== Checking if @elevanaltd/shared-lib was installed ==="
          if [ -d "node_modules/@elevanaltd/shared-lib" ]; then
            echo "✅ Package directory exists"
            echo ""
            echo "=== Package.json exports field ==="
            cat node_modules/@elevanaltd/shared-lib/package.json | grep -A 20 '"exports"'
            echo ""
            echo "=== Directory structure ==="
            ls -la node_modules/@elevanaltd/shared-lib/
            echo ""
            echo "=== dist/client structure ==="
            ls -la node_modules/@elevanaltd/shared-lib/dist/client/ || echo "❌ dist/client/ does not exist"
          else
            echo "❌ Package directory does NOT exist"
            echo "=== Installed @elevanaltd packages ==="
            ls -la node_modules/@elevanaltd/ || echo "❌ No @elevanaltd scope in node_modules"
          fi

      - name: TypeScript check
        run: npm run typecheck

      - name: ESLint check
        run: npm run lint

      - name: Run tests
        run: npm run test -- --run

      - name: Capture Supabase logs on test failure
        if: failure()
        run: |
          echo "=== Supabase Auth Logs ==="
          docker logs supabase_auth_dev || echo "❌ Auth logs not available"
          echo ""
          echo "=== Supabase DB Logs ==="
          docker logs supabase_db_dev || echo "❌ DB logs not available"
          echo ""
          echo "=== Supabase Status ==="
          supabase status || echo "❌ Status not available"

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: dist/
          retention-days: 7
